(define periodicpayment
  '(&& (= (txn closeremainderto) "Zero")
       (= (txn receiver) "Alice")
       (= (txn amount) 100,000)
       (= (txn fee) 10,000)
       (= (% (txn firstvalid) 100,000) 0)
       ;; (&& (> (block time) "Tuesday") (< (block time) "Wednesday"))
       (= (txn lastvalid) (+ 500 (txn firstvalid)))
       ;; (&& (>= (protocol version) 3.0)
       ;;     (<= (protocol version) 3.4))
       (= (len (txn note)) 0)))
