(define split
  '(&& (= (gtxn 1 closeremainderto) "Alice")
       (= (gtxn 1 receiver) "Alice")
       (= (gtxn 2 closeremainderto) "Bob")
       (= (gtxn 2 receiver) "Bob")
       (< (gtxn 1 fee) (/ (gtxn 1 amount) 100))
       (< (gtxn 1 fee) (/ (gtxn 2 amount) 100))
       (> (gtxn 1 amount) (/ (* (+ (gtxn 1 amount) (gtxn 2 amount)) 60) 100))
       (< (gtxn 1 amount) (/ (* (+ (gtxn 1 amount) (gtxn 2 amount)) 61) 100))
       (> (gtxn 2 amount) (/ (* (+ (gtxn 1 amount) (gtxn 2 amount)) 40) 100))
       (< (gtxn 2 amount) (/ (* (+ (gtxn 1 amount) (gtxn 2 amount)) 41) 100))))
